services:
  api1:
    build: .
    networks:
      - dataflow-net

  api2:
    build: .
    networks:
      - dataflow-net

  api3:
    build: .
    networks:
      - dataflow-net

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
      - api3
    networks:
      - dataflow-net

networks:
  dataflow-net:
    driver: bridge